### ISSUE TITLE
Polyscope will not show mesh, but detect it

### ISSUE THREAD

**Issue by rsimanjuntak1** [GeometryCollective/ddg-exercises#8]
I'm trying to do simplicial-complex-operators in Windows 11. Just so I can use the mentioned command (cmake, make, bin/main etc) I used Ubuntu as Windows Subsystem for Linux. Then to connect the graphics I installed Vcxsrv, allowing me to use things like xeyes in in my Ubuntu cmd

I managed to download all the required package to generate the executable main. I did have to do the `cmake -DCMAKE_BUILD_TYPE=Debug ..)` trick mentioned on [here](https://github.com/GeometryCollective/ddg-exercises/issues/1). The problem is when I tried to run "bin/main", while Polyscope run it will not show the mesh. Pictures when I run "bin/main ../../../input/bunny.obj"
<img width="804" alt="image" src="https://user-images.githubusercontent.com/29574917/186347356-ca4796c8-b9b4-4238-815a-640bf609cb2c.png">

it seems Polyscope notice the mesh since it mentions number of vertices and faces. However it will not show the mesh, only plain white.

The weirdest thing is it was working fine in my exact same machine (DELL XPS) when I still had Windows 10. Now I change to Windows 11 this issue appears. I would be extremely grateful for any guidance/thoughts. Happy to cooperate in any way.

**Comment by rsimanjuntak1** [comment]
update: After Nicole Feng's latest update, it was working for a while on my ubuntu WSL (Windows Subsystem Linux) + GWSL as my X-server

Then I performed a windows driver update BIOS, the issue came back again. I know ubuntu GUI is working fine since xeyes, even linux desktop xfce4 is working fine. Thus this issue is between polyscope and some new windows 11 driver causing polyscope not loading the mesh....  a bit frustated now....

**Comment by nzfeng** [comment]
Hm, it does sound like a problem between your updated driver and Polyscope. I'm not sure I can do much except recommend you try switching to a different driver (the NVIDIA ones have not seemed to have issue) or downgrade back to the one that was working before; or use the [Javascript version of the DDG exercises](https://github.com/cmu-geometry/ddg-exercises-js), which are entirely identical to the C++ exercises except that they are in JS.

Just to record some context here on the Github issue, because much of our conversation took place over email... 
In response to these Windows issues, I updated the fork of Polyscope (and its submodules) that ddg-exercises depends on, in case any Polyscope sub-dependencies were updated to better support other drivers. This worked for a while for @rsimanjuntak1 until it didn't. It seems like running in debug mode doesn't help either. Other OpenGL issues, like [the one described here](https://github.com/cmu-geometry/ddg-exercises-js/issues/1) or [here](https://github.com/nmwsharp/polyscope/issues/162),  were resolved by updating operating systems, drivers, etc. or messing around with compiler optimization settings.

**Comment by rsimanjuntak1** [comment]
yeah, I'll make an update if we figured out. At the moment I'm using the Javascript version and ordering an old Macbook 2015 so I can try running polyscope there (I assume that is the original environment Polyscope was build for?). Hopefully better luck once I figure out how to change driver in WSL2.

As a side note, I tried the template project from Polyscope repo, it shows the same behavior loading but not showing the mesh. I'm trying hard to use Polyscope for continuity once I finish all hw, maybe I should not be too fixated on it and try to learn other rendering tools....

I will close the issue for now but thanks a lot for Nicole replying and updating the repo
